# Generated by Django 4.1.1 on 2022-09-23 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("first_app", "0002_rename_accessrecords_accessrecord"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=128)),
                ("last_name", models.CharField(max_length=128)),
                ("email", models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
